version: '3'

services:
  reverse:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pizzaria-app
networks:
  pizzaria-app:
    external: true
