version: '3'

services:
  pizzaria-user:
    build: .
    image: universodapizza/user
    container_name: pizzaria-user
    hostname: pizzaria-user
    environment:
      - FLASK_APP=src/run.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port 5000
    volumes:
      - ./src:/app/src
    networks:
      - pizzaria-app
networks:
  pizzaria-app:
    external: true
